spring.application.name=nexus
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=skillsphere_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=skillsphere_app
spring.datasource.password=infosis@321

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
server.port=8080