spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=skillsphere_db;encrypt=true;trustServerCertificate=true
spring.datasource.username=skillsphere_app
spring.datasource.password=Nexus@12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true